version: '3'

services:
  file-system-http-api:
    build: .
    image: file-system-http-api:${VERSION-latest}
    container_name: file-system-http-api
    networks:
      - default
    depends_on:
      - db
    restart: always
    ports:
      - 9080:80
    volumes:
      - ./app:/var/www/api.xsolla.com/
      - ./upload:/var/www/api.xsolla.com/upload/
    env_file:
      - .env

  db:
    image: mysql:latest
    networks:
      - default
    ports:
      - 3336:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xsolla
    volumes:
      - ./database:/var/lib/mysql

networks:
  default:
    driver: bridge