version: '3'
services:
  app:
    build: .
    container_name: news-feed-app
    networks:
      - news_feed
    depends_on:
      - db
    ports:
      - 9080:80
#    volumes:
#      - ./:/var/www/news-feed/

  db:
    image: mysql:5.5
    container_name: news-feed-db
    networks:
      - news_feed
    ports:
      - 3336:3306
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
    volumes:
      - ./database:/var/lib/mysql

networks:
  news_feed:
    driver: bridge