version: '3'
services:
  file-system-http-api:
    build: .
    image: file-system-http-api:${VERSION-latest}
    container_name: file-system-http-api
    network_mode: bridge
    restart: always
    ports:
      - 9080:80
    #volumes:
    #  - ./:/var/www/api.xsolla.com/
    env_file:
      - .env